version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
    - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
